services:
  _defaults:
    autowire: true
    public: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\EventListener\ResponseListener:
    tags:
      - { name: 'kernel.event_listener', event: Framework\Event\ResponseEvent }
