services:

  #Kernel
  Framework\Kernel\HttpKernel:
    public: true
    arguments:
      - '@Symfony\Component\EventDispatcher\EventDispatcher'
      - '@Framework\Controller\ControllerResolver'
      - '@Framework\Controller\ArgumentResolver'

  #Router
  Framework\Router\RouterFactory: ~

  Symfony\Component\Routing\Router:
    factory: '@Framework\Router\RouterFactory'
    arguments:
      - '@service_container'

  #Controller
  Framework\Controller\ControllerResolver:
    arguments:
      - '@service_container'

  Framework\Controller\ArgumentResolver: ~

  #ExceptionHandler
  Framework\ExceptionHandler\ExceptionHandlerInterface: '@Framework\ExceptionHandler\ExceptionHandler'

  Framework\ExceptionHandler\ExceptionHandler:
    arguments:
      - '@Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer'
      - '%kernel.debug%'
    calls:
      - addRenderer: ['application/json', '@Symfony\Component\ErrorHandler\ErrorRenderer\SerializerErrorRenderer']

  #ExceptionRenderers
  Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer:
    arguments:
      - '%kernel.debug%'

  Symfony\Component\ErrorHandler\ErrorRenderer\SerializerErrorRenderer:
    arguments:
      - '@Symfony\Component\Serializer\SerializerInterface'
      - 'json'
      - '@Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer'
      - '%kernel.debug%'

  #Serializer
  Symfony\Component\Serializer\SerializerInterface: '@Symfony\Component\Serializer\Serializer'

  Symfony\Component\Serializer\Serializer:
    arguments:
      - [
        '@Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer',
        '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
      ]
      - [ '@Symfony\Component\Serializer\Encoder\JsonEncoder' ]

  Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer: ~
  Symfony\Component\Serializer\Normalizer\ObjectNormalizer: ~

  Symfony\Component\Serializer\Encoder\JsonEncoder: ~

  #EventDispatcher
  Symfony\Component\EventDispatcher\EventDispatcher: ~

  event_dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcher'

  #Events
  Framework\EventListener\RouterListener:
    arguments:
      - '@Symfony\Component\Routing\Router'
    tags:
      - { name: 'kernel.event_listener', event: Framework\Event\RequestEvent }

  Framework\EventListener\ExceptionListener:
    arguments:
      - '@Framework\ExceptionHandler\ExceptionHandlerInterface'
    tags:
      - { name: 'kernel.event_listener', event: Framework\Event\ExceptionEvent }
