services:

  #Kernel
  Framework\Kernel\HttpKernel:
    public: true
    arguments:
      - '@Symfony\Component\EventDispatcher\EventDispatcher'
      - '@Framework\Controller\ControllerResolver'
      - '@Framework\Controller\ArgumentResolver'

  #Router
  Framework\Router\RouterFactory: ~

  Symfony\Component\Routing\Router:
    factory: '@Framework\Router\RouterFactory'
    arguments:
      - '@service_container'

  #Controller
  Framework\Controller\ControllerResolver:
    arguments:
      - '@service_container'

  Framework\Controller\ArgumentResolver: ~

  #EventDispatcher
  Symfony\Component\EventDispatcher\EventDispatcher: ~

  event_dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcher'

  #Events
  Framework\EventListener\RouterListener:
    arguments:
      - '@Symfony\Component\Routing\Router'
    tags:
      - { name: 'kernel.event_listener', event: Framework\Event\RequestEvent }
