services:

  #Kernel
  Framework\Kernel\HttpKernel:
    public: true
    arguments:
      - '@service_container'
      - '@event_dispatcher'

  #Router
  Framework\Router\RouterFactory: ~

  Symfony\Component\Routing\Router:
    public: true
    factory: '@Framework\Router\RouterFactory'
    arguments:
      - '@service_container'

  #EventDispatcher
  Symfony\Component\EventDispatcher\EventDispatcher: ~

  event_dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcher'
