monolog:
  handlers:
    # this "file_log" key could be anything
    main:
      type: stream
      # log to var/log/(environment).log
      path: "%kernel.logs_dir%/dev.log"
      # log *all* messages (debug is lowest level)
      level: debug
